# Generated by Django 4.1.3 on 2022-12-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id'], 'verbose_name': '登陆用户', 'verbose_name_plural': '登陆用户'},
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('dev-adm', '超级管理员'), ('dev-manage', '运维'), ('dev-devlop', '普通用户'), ('dev-pm', 'PM'), ('dev-tm', 'TM')], default='dev-manage', max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(help_text='用户名', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='SshUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('password', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='SSH 密码')),
            ],
            options={
                'db_table': 'ssh_user',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
    ]
