# Generated by Django 4.1.3 on 2022-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_account_options_account_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshuser',
            old_name='create_time',
            new_name='created_tm',
        ),
        migrations.RenameField(
            model_name='sshuser',
            old_name='update_time',
            new_name='updated_tm',
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
