# Generated by Django 4.1.3 on 2023-01-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_create_time_sshuser_created_tm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(help_text='用户名', primary_key=True, serialize=False),
        ),
    ]
