# Generated by Django 4.1.3 on 2023-02-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_capitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Static',
            new_name='StaticServers',
        ),
        migrations.AddField(
            model_name='eqcabs',
            name='static_room_name',
            field=models.CharField(default='', max_length=50, verbose_name='归属机房'),
        ),
    ]
