# Generated by Django 4.1.3 on 2023-01-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('static_capitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Static',
            new_name='StaticServers',
        ),
    ]
