# Generated by Django 4.1.3 on 2023-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('cloud_server_type', models.CharField(default='', max_length=50, null=True, verbose_name='业务类型')),
                ('cloud_server_check', models.CharField(default='0', max_length=2, verbose_name='是否核对')),
                ('cloud_server_cost_env', models.CharField(default='', max_length=50, null=True, verbose_name='成本归属')),
                ('cloud_server_login_type', models.CharField(default='', max_length=50, null=True, verbose_name='登陆方式')),
                ('cloud_server_cloud_ownship', models.CharField(default='', max_length=50, null=True, verbose_name='云归属')),
                ('cloud_server_city', models.CharField(default='', max_length=50, null=True, verbose_name='地域')),
                ('cloud_server_cloudid', models.CharField(default='', max_length=50, null=True, verbose_name='实例ID')),
                ('cloud_server_ssh_ip', models.CharField(default='', max_length=50, null=True, verbose_name='内网SSH地址')),
                ('cloud_server_pub_ip', models.CharField(default='', max_length=50, null=True, verbose_name='公网IP')),
                ('cloud_server_owner', models.CharField(default='', max_length=50, null=True, verbose_name='责任人')),
                ('cloud_server_env_type', models.CharField(default='', max_length=50, null=True, verbose_name='环境')),
                ('cloud_server_cloud_type', models.CharField(default='', max_length=50, null=True, verbose_name='公有云版本')),
                ('cloud_server_region', models.CharField(default='', max_length=50, null=True, verbose_name='项目区域')),
                ('cloud_server_number', models.CharField(default='', max_length=50, null=True, verbose_name='项目编号')),
                ('cloud_server_name', models.CharField(default='', max_length=50, null=True, verbose_name='项目名称')),
                ('cloud_server_cost_money', models.CharField(default='', max_length=50, null=True, verbose_name='月成本')),
                ('cloud_server_cloud_name', models.CharField(default='', max_length=50, null=True, verbose_name='公有云实例名')),
                ('cloud_server_mark_tmp', models.CharField(default='', max_length=50, null=True, verbose_name='临时备注')),
                ('cloud_server_status', models.CharField(choices=[('0', '下线'), ('1', '在线')], default='1', max_length=2, verbose_name='运行状态')),
                ('cloud_server_expiration_time', models.DateTimeField(null=True, verbose_name='过期时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cloud_server_number',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'product_type',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='CloudType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cloudtype',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='CloudProjectsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cloud_servers',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='CloudEnvType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='CloudCpType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cloud_cp_type',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
    ]
