# Generated by Django 4.1.3 on 2022-12-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudcapitals',
            old_name='create_time',
            new_name='created_tm',
        ),
        migrations.RenameField(
            model_name='cloudcapitals',
            old_name='update_time',
            new_name='updated_tm',
        ),
        migrations.RenameField(
            model_name='cloudcptype',
            old_name='create_time',
            new_name='created_tm',
        ),
        migrations.RenameField(
            model_name='cloudcptype',
            old_name='update_time',
            new_name='updated_tm',
        ),
        migrations.RenameField(
            model_name='enviroment',
            old_name='create_time',
            new_name='created_tm',
        ),
        migrations.RenameField(
            model_name='enviroment',
            old_name='update_time',
            new_name='updated_tm',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='create_time',
            new_name='created_tm',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='update_time',
            new_name='updated_tm',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='create_time',
            new_name='created_tm',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='update_time',
            new_name='updated_tm',
        ),
        migrations.RenameField(
            model_name='servicesaddr',
            old_name='create_time',
            new_name='created_tm',
        ),
        migrations.RenameField(
            model_name='servicesaddr',
            old_name='update_time',
            new_name='updated_tm',
        ),
    ]
