# Generated by Django 4.1.3 on 2023-01-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_cpus',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='cpu'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_cpus_car',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='cpu卡数'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_datadisks',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='数据盘'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_mems',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_sysdisks',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='系统盘'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_expiration_time',
            field=models.DateTimeField(max_length=500, null=True, verbose_name='过期时间'),
        ),
    ]
