# Generated by Django 4.1.3 on 2023-01-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0002_cloudservers_cloud_server_cpus_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cloudprojectstype',
            table='cloud_project_groups',
        ),
    ]
