# Generated by Django 4.1.3 on 2023-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0003_alter_cloudprojectstype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cloudtype',
            table='cloud_type_name',
        ),
        migrations.CreateModel(
            name='CloudVersionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='名字')),
                ('created_tm', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_tm', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'cloud_project_type',
                'ordering': ['-id'],
                'unique_together': {('name',)},
            },
        ),
    ]
