# Generated by Django 4.1.3 on 2023-01-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0005_remove_cloudservers_cloud_server_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_project_env',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='项目归属'),
        ),
    ]
