# Generated by Django 4.1.3 on 2023-01-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0007_alter_cloudservers_cloud_server_cloud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_cost_money',
            field=models.FloatField(default='0.00', max_length=50, null=True, verbose_name='月成本'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_cpus',
            field=models.PositiveBigIntegerField(default='', max_length=500, null=True, verbose_name='cpu'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_cpus_car',
            field=models.PositiveBigIntegerField(default='', max_length=500, null=True, verbose_name='cpu卡数'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_datadisks',
            field=models.PositiveBigIntegerField(default='', max_length=500, null=True, verbose_name='数据盘'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_expiration_time',
            field=models.CharField(max_length=500, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_mems',
            field=models.PositiveBigIntegerField(default='', max_length=500, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_sysdisks',
            field=models.PositiveBigIntegerField(default='', max_length=500, null=True, verbose_name='系统盘'),
        ),
    ]
