# Generated by Django 4.1.3 on 2023-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0008_alter_cloudservers_cloud_server_cost_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_cpus',
            field=models.PositiveBigIntegerField(default='', null=True, verbose_name='cpu'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_cpus_car',
            field=models.PositiveBigIntegerField(default='', null=True, verbose_name='cpu卡数'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_datadisks',
            field=models.PositiveBigIntegerField(default='', null=True, verbose_name='数据盘'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_mems',
            field=models.PositiveBigIntegerField(default='', null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_sysdisks',
            field=models.PositiveBigIntegerField(default='', null=True, verbose_name='系统盘'),
        ),
    ]
