# Generated by Django 4.1.3 on 2023-01-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0009_alter_cloudservers_cloud_server_cpus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudservers',
            name='cloud_server_cloud_name',
        ),
    ]
