# Generated by Django 4.1.3 on 2023-01-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0010_remove_cloudservers_cloud_server_cloud_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudservers',
            name='cloud_server_mark_tmp',
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_cloud_name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='公有云实例名'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_mark_tmp_2',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='备注2'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_mark_tmp_3',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='备注3'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_mark_tmp_4',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='备注4'),
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_yewu_type',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='业务类型'),
        ),
    ]
