# Generated by Django 4.1.3 on 2023-02-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0011_remove_cloudservers_cloud_server_mark_tmp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudservers',
            old_name='cloud_server_name',
            new_name='cloud_server_all_name',
        ),
        migrations.AddField(
            model_name='cloudservers',
            name='cloud_server_small_name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='项目简称'),
        ),
    ]
