# Generated by Django 4.1.3 on 2023-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_capitals', '0012_rename_cloud_server_name_cloudservers_cloud_server_all_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_cloudid',
            field=models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='实例ID'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_pub_ip',
            field=models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='公网IP'),
        ),
        migrations.AlterField(
            model_name='cloudservers',
            name='cloud_server_ssh_ip',
            field=models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='内网SSH地址'),
        ),
    ]
